nicksnyder/go-i18n

- i18n/bundle/bundle.go
- i18n/bundle/bundle_test.go
- i18n/i18n.go
I'd like to know which language go-i18n decided to use among the candidates caller provided to Tfunc, for example save the language into database for pushing localized content afterwards.
> Export SupportedLanguage

- i18n/bundle/bundle.go
- i18n/bundle/bundle_test.go
- i18n/bundle/structs.go
- i18n/bundle/structs_test.go
- i18n/example_test.go
- i18n/exampletemplate_test.go
- i18n/i18n.go
Fixes #24.
@nicksnyder The `structs` package is quite lightweight. It is also licensed under MIT. I can attempt to extract the `Struct.structFields()` and `Struct.Map()` methods if you would prefer.
> bundle: runtime-reflect structs to map[string]interface{}

- README.md
- goi18n/doc.go
- i18n/language/pluralspec.go
- i18n/language/pluralspec_test.go
Hey, @nicksnyder! Adding Vietnamese (`vi-VN`, `vi`) in here. Used the pluralization rules from here: http://localization-guide.readthedocs.org/en/latest/l10n/pluralforms.html
> i18n/language: add vietnamese pluralspec

- README.md
- i18n/language/pluralspec.go
- i18n/language/pluralspec_test.go
Rules per http://localization-guide.readthedocs.org/en/latest/l10n/pluralforms.html
> i18n/language: add Macedonian

- README.md
- i18n/language/pluralspec.go
- i18n/language/pluralspec_test.go
> i18n/language: add Latvian

- i18n/bundle/bundle.go
- i18n/bundle/bundle_test.go
- i18n/i18n.go
Functions to return a string array of the loaded language's tags and
also the IDs of the each language's translations. These can be used
for tests and verifications purposes once the languages and translations
have been loaded.
> Add LanguageTags and LanguageTranslationIDs functions

- goi18n/doc.go
- goi18n/goi18n.go
- goi18n/merge.go
- goi18n/merge_test.go
- goi18n/testdata/en-us.yaml
- goi18n/testdata/input/yaml/ar-ar.one.json
- goi18n/testdata/input/yaml/ar-ar.two.json
- goi18n/testdata/input/yaml/en-us.one.yaml
- goi18n/testdata/input/yaml/en-us.two.json
- i18n/bundle/bundle.go
- i18n/exampleyaml_test.go
- i18n/translation/template.go
- i18n/translation/translation.go
I believe my translators would be more comfortable with YAML due to it's noiseless syntax, so I added support for it.
I also changed one of the test files used by the merge test from JSON to YAML, to make sure we can merge YAML as well.
I also added an example file identical to the original with the sole exception that it parses a YAML file.
> added yaml support with tests

- goi18n/doc.go
- i18n/bundle/bundle.go
- i18n/bundle/bundle_test.go
- i18n/example_test.go
- i18n/i18n.go
```sh
$ go test ./... -bench=.
PASS
ok  	github.com/nicksnyder/go-i18n/goi18n	0.007s
PASS
ok  	github.com/nicksnyder/go-i18n/i18n	0.004s
BenchmarkTranslateNonPluralWithMap-4             	 1000000	      3343 ns/op
BenchmarkTranslateNonPluralWithStruct-4          	  500000	      4071 ns/op
BenchmarkTranslateNonPluralWithStructPointer-4   	  500000	      5344 ns/op
BenchmarkTranslatePluralWithMap-4                	 1000000	      4363 ns/op
BenchmarkTranslatePluralWithMapAndCountField-4   	  500000	      3845 ns/op
BenchmarkTranslatePluralWithStruct-4             	  300000	      5993 ns/op
BenchmarkTranslatePluralWithStructPointer-4      	  300000	      4641 ns/op
PASS
ok  	github.com/nicksnyder/go-i18n/i18n/bundle	17.785s
BenchmarkNewOperand-4   	^[[A 2000000	       818 ns/op
PASS
ok …
```
> handle Count field from template data

- i18n/bundle/bundle.go
- i18n/bundle/bundle_test.go
TestConcurrent will panic with current master
> Fixes #54 - make bundle safe for concurrent map reads and writes

- i18n/language/language.go
- i18n/language/pluralspec.go
- i18n/language/pluralspec_test.go
This is a follow up to this long-lived Hugo issue:
https://github.com/gohugoio/hugo/issues/3564
This may be improved on in #82 -- but this one is needed just go get it done.
The plan for Hugo's part is:
For all the language codes in use:
1. Check if it is already registered (`GetPluralSpec`)
2. If not, register it as an alias to `GetPluralSpec("en")`
> Export GetPluralSpec

- i18n/language/pluralspec_test.go
- i18n/translations_test.go
avoiding following tests failures:
i18n/translations_test.go:66: Error call has possible formatting directive %v
FAIL	_/root/go-i18n/i18n [build failed]
i18n/language/pluralspec_test.go:73: Errorf format %q has arg spec of wrong type *language.PluralSpec
FAIL	_/root/go-i18n/i18n/language [build failed]
more details in Go1.10 upstream release notes https://tip.golang.org/doc/go1.10#test
> Make tests pass with go1.10

- v2/i18n/localizer_test.go
- v2/internal/message_template.go
- v2/internal/message_template_test.go
fixes https://github.com/nicksnyder/go-i18n/issues/95
> don't panic if translation is empty

- dev.md
- v2/goi18n/merge_command.go
- v2/i18n/bundle.go
- v2/i18n/localizer.go
- v2/internal/plural/codegen/main.go
- v2/internal/plural/codegen/plurals.xml
- v2/internal/plural/rule.go
- v2/internal/plural/rule_gen.go
- v2/internal/plural/rule_gen_test.go
- v2/internal/plural/rule_test.go
- v2/internal/plural/rules.go
- v2/internal/plural/rules_test.go
new cldr data violates an assumption that plural rules are only for base language tags (e.g. pt_PT)
> update cldr data to v33

- v2/i18n/localizer.go
- v2/internal/message_template.go
- v2/internal/template.go
- v2/internal/template_test.go
This PR adds the ability to define custom template engine funcs. It adds a `Funcs` field to the `LocalizeConfig` struct and passes this parameter to `gotemplate.Funcs`.
> adds ability to define custom funcs in LocalizeConfig #99

- README.md
- v2/example/main.go
- v2/goi18n/extract_command_test.go
- v2/i18n/bundle.go
- v2/i18n/bundle_test.go
- v2/i18n/doc.go
- v2/i18n/example_test.go
- v2/i18n/localizer.go
- v2/i18n/localizer_test.go
- v2/internal/parse.go
- v2/internal/parse_test.go
The goal of this PR is to make initializing a new bundle more readable at the call site.
By using struct initialization, it is obvious what `language.English` means (the default language) without having to look at the docs.
This also makes it easier to evolve the API in the future to add more options without making backward incompatible changes to NewBundle (i.e. adding new parameters).
This breaking change is allowed because 2.0 is still in beta.
> Remove i18n.NewBundle and use struct initialization instead

- v2/internal/plural/rules.go
- v2/internal/plural/rules_test.go
fixes https://github.com/nicksnyder/go-i18n/issues/107
> handle zh correctly

- v2/go.mod
Hey Nick!
This PR is to update `v2/go.mod`.  
This issue is related to  https://github.com/nicksnyder/go-i18n/issues/116. Apparently `/v2` is  missed out from the update you did previously :)
> hotfix: Update outdated v2/go.mod

- README.md
Type for `TemplateData` should be `map[string]interface`, because the value for `Count` is integer
> Fixed localizer example

- v2/i18n/localizer.go
- v2/i18n/localizer_test.go
helps https://github.com/nicksnyder/go-i18n/issues/125
cc @bep
> error if message ids mismatch

- v2/i18n/localizer.go
- v2/i18n/localizer_test.go
So a client can react to that particular error situation.
> Export MessageNotFoundErr

- v2/goi18n/extract_command.go
- v2/goi18n/extract_command_test.go
fixes https://github.com/nicksnyder/go-i18n/issues/142
> extract concatenated strings

- v2/internal/message_template.go
- v2/internal/message_template_test.go
Rational:
------------
If you run code example:
```go
package main
import (
"fmt"
"github.com/BurntSushi/toml"
"github.com/nicksnyder/go-i18n/v2/i18n"
"golang.org/x/text/language"
)
func main() {
bundle := &i18n.Bundle{DefaultLanguage: language.English}
bundle.RegisterUnmarshalFunc("toml", toml.Unmarshal)
// No need to load active.en.toml since we are providing default translations.
bundle.ParseMessageFileBytes([]byte(`
[Test1]
one = "One"
other = "Other"
`),
"active.en.toml")
bundle.ParseMessageFileBytes([]byte(`
[Test1]
one = "Один"
other = "Другой"
#few = "Несколько"
#many = "Много"
`), "active.ru.toml")
localizer := i18n.NewLocalizer(bundle, "en")
fmt.Println(fmt.Sprintf("en: %s", localizer.MustLocalize(
&i18n.LocalizeConfig{MessageID: "Test1", PluralCount: 100})))
localizer = …
```
> Provide nice output of plural form not found error

- .travis.yml
This can be removed per Travis docs.
> remove sudo:false

- v2/goi18n/extract_command.go
- v2/goi18n/extract_command_test.go
fixes https://github.com/nicksnyder/go-i18n/issues/160
> escape extracted strings correctly

- v2/internal/message.go
- v2/internal/message_test.go
Treat `null` translations in JSON the same as being not present.
fixes https://github.com/nicksnyder/go-i18n/issues/153
> handle null in json

- v2/internal/plural/codegen/plurals.xml
- v2/internal/plural/codegen/xml.go
- v2/internal/plural/rule_gen.go
- v2/internal/plural/rule_gen_test.go
The build is broken because the rule for `kw` is inconsistent with the examples. Specifically the rule categorizes "1000.0", "10000.0" and "100000.0" as `two` but these are listed as examples for `other`.
```
--- FAIL: TestKw (0.00s)
rule_test.go:30: kw: PluralFormFunc(&plural.Operands{N:1000, I:1000, V:1, W:0, F:0, T:0}) returned "two", <nil>; expected "other"
rule_test.go:30: kw: PluralFormFunc(&plural.Operands{N:10000, I:10000, V:1, W:0, F:0, T:0}) returned "two", <nil>; expected "other"
rule_test.go:30: kw: PluralFormFunc(&plural.Operands{N:100000, I:100000, V:1, W:0, F:0, T:0}) returned "two", <nil>; expected "other"
```
> update to CLDR v35.1 (2019-04-17)

- .travis.yml
- i18n/bundle_test.go
- i18n/message_template.go
- internal/template.go
- internal/template_test.go
fixes https://github.com/nicksnyder/go-i18n/issues/181
helps https://github.com/nicksnyder/go-i18n/issues/182
> Fix data race and optimize performance

- v2/goi18n/extract_command.go
- v2/goi18n/extract_command_test.go
If you specified a constant for message id e.g
```
package main
import "github.com/nicksnyder/go-i18n/v2/i18n"
const constID = "ConstantID"
var m = &i18n.Message{
ID: constID,
Other: "ID is a constant",
}
```
goi18n extract failed with `failed to marshal en strings to toml: toml: Key '' is not a valid table name. Key names cannot be empty.`
> fix(goi18n): could not extract constant message id

- v2/goi18n/extract_command.go
- v2/goi18n/extract_command_test.go
Fixes the issue described in #206 (more specifically, [this comment](https://github.com/nicksnyder/go-i18n/issues/206#issuecomment-592581660)).
In short, if an identifier is used inside a composite literal, e.g.
```go
var x = &i18n.LocalizeConfig{
Funcs: SomeIdentifier,
}
```
and that identifier (in this case, `SomeIdentifier`) is defined in _another file_, the resulting `ast.Ident` will have a nil `Obj` field, which is causing the `goi18n extract` command to panic.
This just adds a simple nil check before accessing the field to prevent the panic from happening.
> Fix panic caused by nil pointer dereference in "extract" command

- v2/goi18n/marshal.go
- v2/goi18n/marshal_test.go
There is no reason `<`, `>`, or `&` need to be escaped in message files.
fixes https://github.com/nicksnyder/go-i18n/issues/217
> Do not encode HTML entities in JSON message files

- v2/goi18n/extract_command.go
- v2/goi18n/extract_command_test.go
fixes https://github.com/nicksnyder/go-i18n/issues/233
> fix escape sequences when extracting string literals

- v2/i18n/bundlefs.go
This commit aims to add a method for loading bundles from fs.FS. The
change is done to be able to get a nice way to load bundles from an
embedded file system.
Since this can be done by implementing the exported API and using
ParseMessageFileBytes externally, this is not a change that is a must
have. Rather a nice shorthand for using the fs.FS.
This is how it can be used:
package main
import (
"embed"
"github.com/nicksnyder/go-i18n/v2/i18n"
)
//go:embed locale.*.json
var LocaleFS embed.FS
func main() {
bundle := i18n.NewBundle(language.English)
bundle.RegisterUnmarshalFunc("json", json.Unmarshal)
bundle.LoadMessageFileFS(LocaleFS, "locale.sv.json")
}
Thanks!
> Add support for loading bundle from fs.FS

- v2/internal/template_test.go
As of go 1.16, the error message in text/template for this specific case has changed.
> Update test to new error message in go 1.16

- .github/workflows/build.yml
- .github/workflows/goreleaser.yml
- .github/workflows/lsif-go.yml
- v2/go.mod
- v2/go.sum
- Go from 1.9 to 1.12 (due to BurntSushi/toml).
- github.com/BurntSushi/toml v1.0.0
- golang.org/x/text v0.3.7
Fixes https://github.com/nicksnyder/go-i18n/issues/267
> Upgrade dependencies

- v2/i18n/localizer.go
I've been stumbling across a frustrating issue with the underlying tag detection from `x/text/language.Matcher`: the detection algorithm will return a tag value based on a given score who can be surprising. 
Because it is not a bug, I just updated the documentation of `Localizer` in order to give some hint for future user.
I did two go-playground to show this more specifically https://go.dev/play/p/TMoszzbeEZ2
Here is a link to a related Github issue in x/text/language: https://github.com/golang/go/issues/49176
> doc(localizer): add specification about language tag detection

- v2/i18n/bundle.go
This PR fixes the misleading comment  on `MustLoadMessageFile` function.
> fix misleading comment on MustLoadMessageFile function

- v2/i18n/localizer.go
- v2/i18n/localizer_test.go
Behavior has changed with #189. Before that, an empty default message returned nil and an error, now it returns "" without error.
This has been detected by mattermost test suit in https://github.com/mattermost/mattermost/pull/21327 which tries to switch all code base to go-i18n v2, see [related discussion](https://github.com/mattermost/mattermost/pull/21327/files#r1365634307)
> Fix Localize regression with empty default message

- i18n/message.go
- i18n/parse.go
- i18n/parse_test.go
> fallback to empty string message `""` when get nil value

- i18n/localizer.go
- i18n/localizer_test.go
Added a must variant of `LocalizeMessage` (like `Localize` & `MustLocalize`)
> Add convenience function `MustLocalizeMessage`

- i18n/bundle_test.go
- i18n/message.go
Fixes https://github.com/nicksnyder/go-i18n/issues/357
> Fix case sensitivity with message keys

- goi18n/extract_command.go
- goi18n/extract_command_test.go
`go-i18n extract` will error if it finds a message ID that has been duplicated but contains different content.
Duplication with the same content is harmless so it will not error in this case to be lenient.
Fixes https://github.com/nicksnyder/go-i18n/issues/332
> Extract errors for duplicate message ids

- i18n/localizer.go
> chore: fix typo in comment
